export enum StarshipsActionTypes {
  FETCH_STARSHIPS = "FETCH_STARSHIPS",
  FETCH_STARSHIPS_SUCCESS = "FETCH_STARSHIPS_SUCCESS",
  FETCH_STARSHIPS_ERROR = "FETCH_STARSHIPS_ERROR",
  SET_STARSHIP_PAGE = "SET_STARSHIP_PAGE",
}
