export enum StarshipImageTypes {
  FETCH_STARSHIP_IMAGE = "FETCH_STARSHIP_IMAGE",
  FETCH_STARSHIP_IMAGE_SUCCESS = "FETCH_STARSHIP_IMAGE_SUCCESS",
  FETCH_STARSHIP_IMAGE_ERROR = "FETCH_STARSHIP_IMAGE_ERROR",
}
