export enum PlanetActionTypes {
  FETCH_PLANET = "FETCH_PLANET",
  FETCH_PLANET_SUCCESS = "FETCH_PLANET_SUCCESS",
  FETCH_PLANET_ERROR = "FETCH_PLANET_ERROR",
  SEARCH_PLANET = "SEARCH_PLANET",
  SET_PLANET_PAGE = "SET_PLANET_PAGE",
}
