export enum PeopleActionTypes {
  FETCH_PEOPLE = "FETCH_PEOPLE",
  FETCH_PEOPLE_SUCCESS = "FETCH_PEOPLE_SUCCESS",
  FETCH_PEOPLE_ERROR = "FETCH_PEOPLE_ERROR",
  SET_PEOPLE_PAGE = "SET_PEOPLE_PAGE",
}
